name: Test
on:
    push:
    pull_request:

# jobs запускаются параллельно, если не указана последовательность
jobs:
    my_build_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
      steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
          - uses: actions/checkout@v3

          - name: IAM Token
            id: issue-iam-token
            uses: yc-actions/yc-iam-token@v1
            with:
              yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
              
          - name: Echo test iam
            run: |
              echo "$IAM" | base64
            env:
                IAM: ${{ steps.issue-iam-token.outputs.token }}
              
          - name: Import secrets
            uses: mimbol22/yandex-lockbox@v1
            with:
              iam_token: ${{ steps.issue-iam-token.outputs.token }}
              folder_id: ${{ secrets.YC_FOLDER_ID }}
              secret_prefix: DEV_
              is_clean_prefix: false
              
          - name: Echo test secret
            run: |
              echo "$LOCKBOX_DEV_SUPER_SECRET_KEY" | base64
            env:
                LOCKBOX_DEV_SUPER_SECRET_KEY: ${{ vars.LOCKBOX_DEV_SUPER_SECRET_KEY }}
